@echo off
setlocal EnableExtensions EnableDelayedExpansion
set "BASE=C:\Users\CB\Desktop\BALI_ROCKET_CRYPTO_COMMAND_V011B_BAD_PYTHON_HOTFIX_FULL_BUILD"
set "APP=%BASE%\bali_rocket_crypto_command_v011b"
set "REPORTS=%APP%\shared_data\reports"
set "TOOLS=%APP%\tools\BALI_FOREVER_AUTOPATCH_ENGINE"
set "STARTER=%BASE%\BALI_THEMED_FOREVER_STARTER.bat"
set "ORIG_V037=%BASE%\BALI_THEMED_FOREVER_STARTER_ORIGINAL_V037.bat"
set "ORIG_V030=%BASE%\BALI_THEMED_FOREVER_STARTER_ORIGINAL_V030.bat"
set "INSTALL_REPORT=%REPORTS%\BALI_V037_AUTOPATCH_ENGINE_INSTALL_REPORT.txt"

if not exist "%REPORTS%" mkdir "%REPORTS%" >nul 2>nul
if not exist "%TOOLS%" mkdir "%TOOLS%" >nul 2>nul

> "%INSTALL_REPORT%" echo BALI V037 FOREVER AUTOPATCH ENGINE INSTALL REPORT
>> "%INSTALL_REPORT%" echo Generated: %date% %time%
>> "%INSTALL_REPORT%" echo SAFETY=LIVE_ORDERS_OFF ^| CHAMPION_LOCK_LOCKED ^| NO_API_KEYS
>> "%INSTALL_REPORT%" echo VERSION=V037_FOREVER_AUTOPATCH_ENGINE_INSTALLER
>> "%INSTALL_REPORT%" echo PYTHON_USED=NO
>> "%INSTALL_REPORT%" echo UPDATE_DOCK_USED=NO
>> "%INSTALL_REPORT%" echo BASE=%BASE%
>> "%INSTALL_REPORT%" echo APP=%APP%
>> "%INSTALL_REPORT%" echo REPORTS=%REPORTS%
>> "%INSTALL_REPORT%" echo STARTER=%STARTER%

if not exist "%BASE%" (
  >> "%INSTALL_REPORT%" echo RESULT=FAIL_BASE_NOT_FOUND
  notepad "%INSTALL_REPORT%"
  exit /b 1
)
if not exist "%APP%" (
  >> "%INSTALL_REPORT%" echo RESULT=FAIL_APP_NOT_FOUND
  notepad "%INSTALL_REPORT%"
  exit /b 1
)
if not exist "%STARTER%" (
  >> "%INSTALL_REPORT%" echo RESULT=FAIL_REAL_FOREVER_STARTER_NOT_FOUND
  notepad "%INSTALL_REPORT%"
  exit /b 1
)

rem Preserve a true original. Prefer the already-known original V030 if present.
if exist "%ORIG_V030%" (
  copy /y "%ORIG_V030%" "%ORIG_V037%" >nul
  >> "%INSTALL_REPORT%" echo ORIGINAL_SOURCE=%ORIG_V030%
) else (
  copy /y "%STARTER%" "%ORIG_V037%" >nul
  >> "%INSTALL_REPORT%" echo ORIGINAL_SOURCE=%STARTER%
)

copy /y "%~dp0payload\BALI_THEMED_FOREVER_STARTER_V037_WRAPPER.bat" "%STARTER%" >nul
copy /y "%~dp0payload\BALI_AUTOPATCH_STATUS_OPEN_NOW.bat" "%BASE%\BALI_AUTOPATCH_STATUS_OPEN_NOW.bat" >nul
copy /y "%~dp0payload\BALI_AUTOPATCH_ENGINE_HEALTH_CHECK_NOW.bat" "%BASE%\BALI_AUTOPATCH_ENGINE_HEALTH_CHECK_NOW.bat" >nul
copy /y "%~dp0payload\BALI_THEMED_FOREVER_STARTER_V037_WRAPPER.bat" "%TOOLS%\BALI_THEMED_FOREVER_STARTER_V037_WRAPPER.bat" >nul
copy /y "%~dp0payload\BALI_AUTOPATCH_STATUS_OPEN_NOW.bat" "%TOOLS%\BALI_AUTOPATCH_STATUS_OPEN_NOW.bat" >nul
copy /y "%~dp0payload\BALI_AUTOPATCH_ENGINE_HEALTH_CHECK_NOW.bat" "%TOOLS%\BALI_AUTOPATCH_ENGINE_HEALTH_CHECK_NOW.bat" >nul

> "%APP%\tools\V037_FOREVER_AUTOPATCH_ENGINE_MARKER.txt" echo VERSION=V037_FOREVER_AUTOPATCH_ENGINE
>> "%APP%\tools\V037_FOREVER_AUTOPATCH_ENGINE_MARKER.txt" echo INSTALLED=%date% %time%
>> "%APP%\tools\V037_FOREVER_AUTOPATCH_ENGINE_MARKER.txt" echo PYTHON_USED=NO
>> "%APP%\tools\V037_FOREVER_AUTOPATCH_ENGINE_MARKER.txt" echo UPDATE_DOCK_USED=NO
>> "%APP%\tools\V037_FOREVER_AUTOPATCH_ENGINE_MARKER.txt" echo STARTER=%STARTER%

>> "%INSTALL_REPORT%" echo WRITTEN_STARTER=%STARTER%
>> "%INSTALL_REPORT%" echo WRITTEN_ORIGINAL_BACKUP=%ORIG_V037%
>> "%INSTALL_REPORT%" echo WRITTEN_TOOLS=%TOOLS%
>> "%INSTALL_REPORT%" echo WRITTEN_STATUS_OPENER=%BASE%\BALI_AUTOPATCH_STATUS_OPEN_NOW.bat
>> "%INSTALL_REPORT%" echo WRITTEN_HEALTH_CHECK=%BASE%\BALI_AUTOPATCH_ENGINE_HEALTH_CHECK_NOW.bat
>> "%INSTALL_REPORT%" echo RESULT=PASS_V037_FOREVER_AUTOPATCH_ENGINE_INSTALLED
notepad "%INSTALL_REPORT%"
exit /b 0
