@echo off
setlocal EnableExtensions EnableDelayedExpansion

title BALI V021 GOLDEN STANDARD MARKER

echo ==========================================================
echo  BALI V021 GOLDEN ONE-CLICK PATCH STANDARD
echo ==========================================================
echo Safety: live orders stay OFF; no API keys; no private endpoints.
echo.

set "DESKTOP=%USERPROFILE%\Desktop"
set "REPORT_DESKTOP=%DESKTOP%\BALI_V021_GOLDEN_STANDARD_REPORT.txt"
set "KNOWN_ROOT=%USERPROFILE%\Desktop\BALI_ROCKET_CRYPTO_COMMAND_V011B_BAD_PYTHON_HOTFIX_FULL_BUILD\bali_rocket_crypto_command_v011b"

> "%REPORT_DESKTOP%" echo BALI V021 GOLDEN STANDARD REPORT
>> "%REPORT_DESKTOP%" echo Generated: %DATE% %TIME%
>> "%REPORT_DESKTOP%" echo SAFETY=LIVE_ORDERS_OFF ^| CHAMPION_LOCK_LOCKED ^| NO_API_KEYS
>> "%REPORT_DESKTOP%" echo VERSION=V021_GOLDEN_ONE_CLICK_PATCH_STANDARD
>> "%REPORT_DESKTOP%" echo RULE=USE_NO_PYTHON_ONE_CLICK_RUNNER_FOR_FUNCTIONAL_PATCHES
>> "%REPORT_DESKTOP%" echo UPDATE_DOCK=TEST_ONLY_UNTIL_VALIDATOR_FIXED
>> "%REPORT_DESKTOP%" echo PYTHON_USED=NO

if exist "%KNOWN_ROOT%\shared_data\reports" (
  set "BALI_ROOT=%KNOWN_ROOT%"
) else (
  for /d %%D in ("%USERPROFILE%\Desktop\BALI_ROCKET_CRYPTO_COMMAND*" "%USERPROFILE%\Desktop\*BALI*") do (
    if exist "%%~fD\shared_data\reports" set "BALI_ROOT=%%~fD"
    if exist "%%~fD\bali_rocket_crypto_command_v011b\shared_data\reports" set "BALI_ROOT=%%~fD\bali_rocket_crypto_command_v011b"
  )
)

if not defined BALI_ROOT (
  >> "%REPORT_DESKTOP%" echo RESULT=FAIL_BALI_ROOT_NOT_FOUND
  notepad "%REPORT_DESKTOP%"
  exit /b 1
)

set "REPORTS=%BALI_ROOT%\shared_data\reports"
set "TOOLS=%BALI_ROOT%\tools"
if not exist "%REPORTS%" mkdir "%REPORTS%"
if not exist "%TOOLS%" mkdir "%TOOLS%"

>> "%REPORT_DESKTOP%" echo ROOT=%BALI_ROOT%
>> "%REPORT_DESKTOP%" echo REPORTS=%REPORTS%

> "%TOOLS%\V021_GOLDEN_ONE_CLICK_PATCH_STANDARD_MARKER.txt" echo V021 golden standard installed %DATE% %TIME%
> "%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.txt" echo VERSION=V021_GOLDEN_ONE_CLICK_PATCH_STANDARD
>> "%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.txt" echo RULE=FUNCTIONAL_PATCHES_USE_NO_PYTHON_ONE_CLICK_RUNNER
>> "%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.txt" echo UPDATE_DOCK=TEST_ONLY_UNTIL_VALIDATOR_FIXED
>> "%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.txt" echo SAFETY=LIVE_ORDERS_OFF ^| CHAMPION_LOCK_LOCKED ^| NO_API_KEYS
>> "%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.txt" echo RESULT=PASS_V021_GOLDEN_STANDARD_WRITTEN_NO_PYTHON

> "%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.json" echo {"version":"V021_GOLDEN_ONE_CLICK_PATCH_STANDARD","functional_patch_install_path":"NO_PYTHON_ONE_CLICK_RUNNER","update_dock":"TEST_ONLY_UNTIL_VALIDATOR_FIXED","live_orders_allowed":false,"api_keys_allowed":false,"champion_lock":"LOCKED","result":"PASS_V021_GOLDEN_STANDARD_WRITTEN_NO_PYTHON"}
> "%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.md" echo # Bali V021 Golden One-Click Patch Standard
>> "%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.md" echo.
>> "%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.md" echo Functional patches should use the no-Python one-click runner. Update Dock is test-only until its validator/apply path is fixed.

>> "%REPORT_DESKTOP%" echo WRITTEN_MARKER=%TOOLS%\V021_GOLDEN_ONE_CLICK_PATCH_STANDARD_MARKER.txt
>> "%REPORT_DESKTOP%" echo WRITTEN_STATUS=%REPORTS%\BALI_CAPABILITY_STATUS_V021_GOLDEN_STANDARD.txt
>> "%REPORT_DESKTOP%" echo RESULT=PASS_V021_GOLDEN_STANDARD_WRITTEN_NO_PYTHON

copy /y "%REPORT_DESKTOP%" "%REPORTS%\BALI_V021_GOLDEN_STANDARD_REPORT.txt" >nul 2>nul
notepad "%REPORT_DESKTOP%"
exit /b 0
