@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 >nul 2>nul
set "BALI_ROOT=C:\Users\CB\Desktop\BALI_ROCKET_CRYPTO_COMMAND_V011B_BAD_PYTHON_HOTFIX_FULL_BUILD\bali_rocket_crypto_command_v011b"
set "INBOX=C:\Users\CB\Desktop\BALI_ROCKET_CRYPTO_COMMAND_V011B_BAD_PYTHON_HOTFIX_FULL_BUILD\bali_rocket_crypto_command_v011b\BALI_AUTO_PATCH_INBOX"
set "APPLIED=C:\Users\CB\Desktop\BALI_ROCKET_CRYPTO_COMMAND_V011B_BAD_PYTHON_HOTFIX_FULL_BUILD\bali_rocket_crypto_command_v011b\BALI_AUTO_PATCH_APPLIED"
set "QUARANTINE=C:\Users\CB\Desktop\BALI_ROCKET_CRYPTO_COMMAND_V011B_BAD_PYTHON_HOTFIX_FULL_BUILD\bali_rocket_crypto_command_v011b\BALI_AUTO_PATCH_QUARANTINE"
set "REPORTS=C:\Users\CB\Desktop\BALI_ROCKET_CRYPTO_COMMAND_V011B_BAD_PYTHON_HOTFIX_FULL_BUILD\bali_rocket_crypto_command_v011b\shared_data\reports"
set "LANE_REPORT=%REPORTS%\BALI_AUTO_PATCH_LANE_REPORT.txt"
set "TMP=%BALI_ROOT%\_AUTO_PATCH_TEMP"
mkdir "%INBOX%" "%APPLIED%" "%QUARANTINE%" "%REPORTS%" >nul 2>nul
> "%LANE_REPORT%" echo BALI AUTO PATCH LANE REPORT
>> "%LANE_REPORT%" echo Generated: %DATE% %TIME%
